PROJECT_ROOT: ~/hdelecki/ford_ws/SequentialPerceptionPipeline/
NUSCENES_DATAROOT: /scratch/hdelecki/ford/data/sets/nuscenes/v1.0-mini
NUSCENES_VERSION: v1.0-mini # v1.0-mini or v1.0-trainval
NUSCENES_SPLIT: mini_val # train or val

# Detection
MODEL_CONFIG: /home/hdelecki/ford_ws/SequentialPerceptionPipeline/configs/detection/cbgs_pp_multihead.yaml
MODEL_CKPT: /home/hdelecki/ford_ws/OpenPCDet/models/pp_multihead_nds5823_updated.pth
PNTCLOUD_EXT: .pkl
DETECTION_RESULTS: /scratch/hdelecki/ford/output/detection/results/detection_results.json


# TRACKING:
#   DATA_ASSOCIATION: greedy # greedy or hungarian
#   MODEL: cv # cv or cvtr
#   TRACKING_RESULTS: /scratch/hdelecki/ford/tracking/results

# PREDICTION:
#   PREDICTION_RESULTS: /scratch/hdelecki/ford/prediction/results


  